// <auto-generated />
using System;
using ControleVeterinario.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleVeterinario.Repositorio.Migrations
{
    [DbContext(typeof(ContextoBanco))]
    partial class ContextoBancoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleVeterinario.Dominio.RFIDs.RFID", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<string>("CodigoRFID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RFID");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DateTime")
                        .HasColumnName("DataCadastro");

                    b.Property<bool>("EmUso")
                        .HasColumnType("bit")
                        .HasColumnName("EmUso");

                    b.HasKey("Codigo");

                    b.ToTable("CV_RFID", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
