USE [master]
GO

/****** Object:  Database [DB_ControleVeterinario]    Script Date: 12/11/2022 23:20:04 ******/
CREATE DATABASE [DB_ControleVeterinario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_ControleVeterinario', FILENAME = N'B:\Desenv\DataBase\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_ControleVeterinario.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_ControleVeterinario_log', FILENAME = N'B:\Desenv\DataBase\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_ControleVeterinario_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_ControleVeterinario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_ControleVeterinario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_ControleVeterinario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_ControleVeterinario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_ControleVeterinario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_ControleVeterinario] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_ControleVeterinario] SET  MULTI_USER 
GO

ALTER DATABASE [DB_ControleVeterinario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_ControleVeterinario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_ControleVeterinario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_ControleVeterinario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_ControleVeterinario] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_ControleVeterinario] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_ControleVeterinario] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_ControleVeterinario] SET  READ_WRITE 
GO

